var ChanCheConfig = {};

ChanCheConfig.Enum = {
	GAME_MODE_NIUNIUSHANGZHUANG: 0,
	GAME_MODE_GUDINGZHUANGJIA: 1,
	GAME_MODE_ZIYOUQIANGZHUANG: 2,
	GAME_MODE_MINGPAIQIANGZHUANG: 3,
	GAME_MODE_TONGBINIUNIU: 4,

	GAME_STATE_UNKNOWN: 0,
	GAME_STATE_QIANG_ZHUANG: 1,
	GAME_STATE_YA_FEN: 2,
	GAME_STATE_KAN_PAI: 3,

	CHAN_CHE_TYPE_MA_SHA: 0,
	CHAN_CHE_TYPE_MU_CHAN: 1,
	CHAN_CHE_TYPE_TIE_CHAN: 2,
	CHAN_CHE_TYPE_TONG_CHAN: 3,
	CHAN_CHE_TYPE_YIN_CHAN: 4,
	CHAN_CHE_TYPE_JIN_CHAN: 5,
	CHAN_CHE_TYPE_ZHI_ZUN_CHAN: 6,

	NN_CARD_TYPE_WU_NIU: 0,
	NN_CARD_TYPE_NORMAL_NIU: 1,
	NN_CARD_TYPE_SHUNZI: 2,
	NN_CARD_TYPE_WUHUA: 3,
	NN_CARD_TYPE_TONGHUA: 4,
	NN_CARD_TYPE_HULU: 5,
	NN_CARD_TYPE_ZHADAN: 6
};

ChanCheConfig.yaFen = [];
ChanCheConfig.yaFen[ChanCheConfig.Enum.GAME_MODE_NIUNIUSHANGZHUANG] = [[1, 2], [2, 4], [4, 8], [5, 10]];
ChanCheConfig.yaFen[ChanCheConfig.Enum.GAME_MODE_GUDINGZHUANGJIA] = [[1, 2], [2, 4], [4, 8], [5, 10]];
ChanCheConfig.yaFen[ChanCheConfig.Enum.GAME_MODE_ZIYOUQIANGZHUANG] = [[1, 2], [2, 4], [4, 8], [5, 10]];
ChanCheConfig.yaFen[ChanCheConfig.Enum.GAME_MODE_MINGPAIQIANGZHUANG] = [[1, 2], [2, 4], [4, 8], [5, 10]];
ChanCheConfig.yaFen[ChanCheConfig.Enum.GAME_MODE_TONGBINIUNIU] = [[1], [2], [4], [5]];

exports.ChanCheConfig = ChanCheConfig;